// Fake data
export const products = [
  {
    store: "Amazon",
    productName: "Fairlife",
    description: "Lactose Free Fat Free Ultra Filtered Milk, 52 fl oz",
    price: 4.02,
    ratings: 5,
    imageSrc: "/product.png",
  },
  {
    store: "Walmart",
    productName: "Fairlife",
    description: "Lactose Free Fat Free Ultra Filtered Milk, 52 fl oz",
    price: 4.28,
    ratings: 4.5,
    imageSrc: "/product.png",
  },
  {
    store: "Target.com",
    productName: "Fairlife",
    description: "Lactose Free Fat Free Ultra Filtered Milk, 52 fl oz",
    price: 4.48,
    ratings: 4,
    imageSrc: "/product.png",
  },
  {
    store: "Flipkart",
    productName: "Fairlife",
    description: "Lactose Free Fat Free Ultra Filtered Milk, 52 fl oz",
    price: 4.68,
    ratings: 4.7,
    imageSrc: "/product.png",
  },
  {
    store: "Country Delight",
    productName: "Fairlife",
    description: "Lactose Free Fat Free Ultra Filtered Milk, 52 fl oz",
    price: 5.48,
    ratings: 3.9,
    imageSrc: "/product.png",
  },
  {
    store: "BigBasket",
    productName: "Fairlife",
    description: "Lactose Free Fat Free Ultra Filtered Milk, 52 fl oz",
    price: 6.1,
    ratings: 3.5,
    imageSrc: "/product.png",
  },
  {
    store: "Creamline Dairy",
    productName: "Fairlife",
    description: "Lactose Free Fat Free Ultra Filtered Milk, 52 fl oz",
    price: 5.78,
    ratings: 4.2,
    imageSrc: "/product.png",
  },
  {
    store: "Pravarshe Industries",
    productName: "Fairlife",
    description: "Lactose Free Fat Free Ultra Filtered Milk, 52 fl oz",
    price: 6.48,
    ratings: 3.8,
    imageSrc: "/product.png",
  },
  {
    store: "Heritage Foods",
    productName: "Fairlife",
    description: "Lactose Free Fat Free Ultra Filtered Milk, 52 fl oz",
    price: 6.82,
    ratings: 3.9,
    imageSrc: "/product.png",
  },
];

